controllers/AdminController.php
<?php namespace app\controllers;

use app\models\Admin;
use app\models\Cloth;
use app\models\Contact;
use app\models\Form;
use app\models\Language;
use app\models\Message;
use app\models\Product;
use app\models\Repair;
use app\models\Service;
use app\models\SourceMessage;
use app\models\User;
use app\modules\content\BaseContent;
use app\modules\content\ContentAsset;
use app\modules\content\models\Content;
use app\modules\media\MediaAsset;
use nox\components\http\userAgent\UserAgentParser;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;
use app\models\LoginForm;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\View;

class AdminController extends Controller {

    public $layout = 'admin-main';

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [
                            'index', 'products', 'edit', 'leads', 'contacts', 'settings', 'languages',
                            'users', 'translations', 'privacy-policy', 'logout', 'ajax'
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['login', 'registration'],
                        'allow' => true,
                        'roles' => ['?']
                    ]
                ],
            ]
        ];
    }

    public function actions() { return ['error' => ['class' => 'yii\web\ErrorAction']]; }

    public function beforeAction($action) {
        if (!in_array($action->id, ['login', 'logout', 'ajax'])) {
            ContentAsset::register($this->view);
            MediaAsset::register($this->view);
            $this->view->registerJs('Admin.ajax.url = "'.Url::toRoute(['admin/ajax']).'";', View::POS_END);
        }
        return parent::beforeAction($action);
    }

    public function actionIndex() {
        $this->view->title = 'Dashboard nanoV2';
        return $this->render('index');
    }

    public function actionProducts() {
        $this->view->title = Yii::t('admin', 'Продукция');
        $this->view->registerJsFile('/js/admin/product.js');
        return $this->render('products', [
            'products' => Product::find()->orderBy(['priority' => SORT_ASC])->asArray()->all()
        ]);
    }

//    public function actionRepairs() {
//        $this->view->title = Yii::t('admin', 'Типы ремонта');
//        $this->view->registerJsFile('/js/admin/service.js');
//        $this->view->registerJs('Service.Model = "Repair";', View::POS_END);
//        return $this->render('repairs', [
//            'repairs' => Repair::find()->orderBy(['priority' => SORT_ASC])->asArray()->all()
//        ]);
//    }

//    public function actionClothes() {
//        $this->view->title = Yii::t('admin', 'Виды одежды');
//
//        $this->view->registerJsFile('/js/admin/service.js');
//        $this->view->registerJs('Service.Model = "Cloth";', View::POS_END);
//        return $this->render('clothes', [
//            'clothes' => Cloth::find()->orderBy(['priority' => SORT_ASC])->asArray()->all()
//        ]);
//    }

    public function actionEdit() {
        $this->view->title = Yii::t('admin', 'Лэндинг');
        return $this->render('edit');
    }

    public function actionLeads() {
        $this->view->title = Yii::t('admin', 'Заявки');
        $searchQuery = [
            'query' => Yii::$app->request->cookies->getValue('leads-search-query', ''),
            'type' => Yii::$app->request->cookies->getValue('leads-search-type', Form::TYPE_ALL),
            'status' => Yii::$app->request->cookies->getValue('leads-search-status', Form::STATUS_ALL),
            'currentPage' => Yii::$app->request->cookies->getValue('leads-search-currentPage', 1),
            'pageLimit' => Yii::$app->request->cookies->getValue('leads-search-pageLimit', Form::LIMIT_10)
        ];
        if ($apiKey = Content::get(CONTENT_CONTACT_API_KEY, BaseContent::OBJ_NOT_SET, BaseContent::LANG_NOT_SET)) {
            $this->view->registerJsFile(implode('=', ['//maps.googleapis.com/maps/api/js?key', $apiKey]), ['position' => View::POS_HEAD]);
        }
        $this->view->registerJs('Admin.searchQuery = '.json_encode($searchQuery).';', View::POS_END);
        return $this->render('leads', Form::search($searchQuery));
    }

    public function actionContacts() {
        $this->view->title = Yii::t('admin', 'Контакты');
        if ($apiKey = Content::get(CONTENT_CONTACT_API_KEY, BaseContent::OBJ_NOT_SET, BaseContent::LANG_NOT_SET)) {
            $this->view->registerJsFile(implode('=', ['//maps.googleapis.com/maps/api/js?key', $apiKey]), ['position' => View::POS_HEAD]);
        }
        $lat = Content::get(CONTENT_CONTACT_MAP_LAT, BaseContent::OBJ_NOT_SET, BaseContent::LANG_NOT_SET);
        $lng = Content::get(CONTENT_CONTACT_MAP_LNG, BaseContent::OBJ_NOT_SET, BaseContent::LANG_NOT_SET);
        $zoom = Content::get(CONTENT_CONTACT_MAP_ZOOM, BaseContent::OBJ_NOT_SET, BaseContent::LANG_NOT_SET);
        return $this->render('contacts', [
            'lat' => $lat ? $lat : BaseContent::DEFAULT_MAP_LAT,
            'lng' => $lng ? $lng : BaseContent::DEFAULT_MAP_LNG,
            'zoom' => $zoom ? $zoom : BaseContent::DEFAULT_MAP_ZOOM,
        ]);
    }

    public function actionSettings() {
        $this->view->title = Yii::t('admin', 'Настройки');
        return $this->render('settings');
    }

    public function actionLanguages() {
        $this->view->title = Yii::t('admin', 'Языки');
        return $this->render('languages');
    }

    public function actionUsers() {
        $this->view->title = Yii::t('admin', 'Пользователи');
        return $this->render('users');
    }

    public function actionTranslations() {
        $this->view->title = Yii::t('admin', 'Переводы');
        Yii::$app->cache->delete('site-languages');
        return $this->render('translations', [
            'languages' => Language::getLanguages(),
            'translations' => SourceMessage::getTranslations()
        ]);
    }

    public function actionPrivacyPolicy() {
        $this->view->title = Yii::t('admin', 'Политика конфиденциальности');
        return $this->render('privacy-policy');
    }

    public function actionLogin() {
        if (Yii::$app->user->isGuest) {
            $this->view->title = Yii::t('admin', 'Авторизация');
            $model = new LoginForm();
            if ($model->load(Yii::$app->request->post()) && $model->login()) { return $this->goBack(); }
            $model->password = '';
            return $this->render('login', ['model' => $model]);
        } else { return $this->goHome(); }
    }

    public function actionLogout() {
        Yii::$app->user->logout();
        return $this->goHome();
    }

    public function actionRegistration($token) {
        if ($user = User::findOne(['token' => $token, 'status' => User::STATUS_INVITED])) {
            $user->status = User::STATUS_ACTIVE;
            $user->token = null;
            if ($user->save()) {
                Yii::$app->user->login($user);
                return $this->redirect(['admin/index']);
            } else { die('Unable to update user'); }
        } else { throw new NotFoundHttpException(); }
    }

    public function actionAjax() {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $result = ['result' => false, 'error' => [], 'post' => $post = Yii::$app->request->post()];
        if (isset($post['method'])) {
            switch ($post['method']) {
                case 'fetchLanguages': $result = ['result' => true, 'html' => $this->renderAjax('languages')];
                    break;
                case 'fetchLanguageForm': $result = [
                    'result' => true, 'html' => $this->renderAjax('language-form', [
                        'language' => Language::findOne($post['langID'])
                    ])
                ];
                    break;
                case 'saveModelField': $result['result'] = Admin::saveModelField($post['model'], $post['field'], $post['ID'], $post['value']);
                    break;

                //Language
                case 'addLanguage': $result = Language::create();
                    break;
                case 'setLanguageDefault': $result['result'] = Language::setDefault($post['langID']);
                    break;
                case 'setLanguageSource': $result['result'] = Language::setSource($post['langID']);
                    break;
                case 'removeLanguage': $result['result'] = Language::remove($post['langID']);
                    break;

                //Translations
                case 'refreshTranslations': $result['result'] = SourceMessage::refreshTranslations(); sleep(2);
                    break;
                case 'saveTranslation': $result['result'] = Message::updateAll(['translation' => $post['value']], [
                    'id' => $post['messageID'], 'language' => $post['langCode']
                ]);
                    break;

                //Contacts
                case 'fetchContactList': $result = ['result' => true, 'html' => $this->renderAjax('contact-list')];
                    break;
                case 'addContact': $result = Contact::add($post['typeID']);
                    break;
                case 'selectPrimaryContact': $result['result'] = Contact::selectPrimary($post['contactID']);
                    break;
                case 'changeSelectedContact': $result['result'] = Contact::updateAll(['selected' => $post['state']], ['id' => $post['contactID']]);
                    break;
                case 'raiseContactPriority': $result['result'] = Contact::raisePriority($post['contactID']);
                    break;
                case 'lowerContactPriority': $result['result'] = Contact::lowerPriority($post['contactID']);

controllers/SiteController.php
<?php namespace app\controllers;

use app\models\Form;
use app\models\Product;
use app\modules\content\BaseContent;
use app\modules\content\models\Content;
use Yii;
use yii\web\Controller;
use yii\web\Response;

class SiteController extends Controller {

    public function actions() { return ['error' => ['class' => 'yii\web\ErrorAction']]; }

//    public function beforeAction($action) {
//        return parent::beforeAction($action);
//    }

    public function actionIndex() {
        $this->view->registerMetaTag([
            'name' => 'title',
            'content' => Yii::$app->view->title = Content::get(CONTENT_SEO_TITLE, BaseContent::OBJ_NOT_SET)
        ]);
        $this->view->registerMetaTag([
            'name' => 'description',
            'content' => Content::get(CONTENT_SEO_DESCRIPTION, BaseContent::OBJ_NOT_SET)
        ]);
        return $this->render('index', [
            'products' => Product::find()->select(['id', 'name', 'auctionPrice', 'marketPrice'])->where([
                'status' => Product::STATUS_ACTIVE
            ])->orderBy(['priority' => SORT_ASC])->asArray()->all()
        ]);
    }

    public function actionPrivacyPolicy() {
        $this->view->title = Yii::t('app', 'Политика конфиденциальности');
        return $this->render('privacy-policy', [
            'privacyPolicy' => Content::get(CONTENT_PRIVACY_POLICY_TEXT, BaseContent::OBJ_NOT_SET)
        ]);
    }

    public function actionRobots() {
        Yii::$app->response->headers->set('Content-type', 'text/plain');
        Yii::$app->response->format = Response::FORMAT_RAW;
        $siteIndex = Content::get(CONTENT_SEO_INDEXATION, BaseContent::OBJ_NOT_SET, BaseContent::LANG_NOT_SET);
        return implode(PHP_EOL, [
            'User-agent: *', 'Disallow: /admin', $siteIndex ? 'Allow: /' : 'Disallow: /', 'Host: '.Yii::$app->request->hostInfo
        ]);
    }

    public function actionAjax() {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $result = ['result' => false, 'error' => [], 'post' => $post = Yii::$app->request->post()];
        if (isset($post['method'])) {
            switch ($post['method']) {
                case 'formSubmit': $result = Form::formSubmit($post['type'], $post['data']);
                    break;

                default: $result['error'][] = 'Unknown method'; break;
            }
        }
        return $result;
    }
}

views/layouts/admin-header.php
<?php
/**
 * @var $this yii\web\View
 */

use app\models\Language;
use yii\helpers\Url;
use app\models\User;
use app\modules\content\models\Content;
?>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= Url::toRoute(['admin/index']) ?>">
                <span class="glyphicon glyphicon-heart"></span>
            </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li <?= Yii::$app->controller->action->id == 'products' ? 'class="active"' : '' ?>>
                    <a href="<?= Url::toRoute(['admin/products']) ?>">
                        <span class="glyphicon glyphicon-star"></span>
                        <?= Yii::t('admin', 'Продукция') ?>
                    </a>
                </li>
                <li <?= Yii::$app->controller->action->id == 'edit' ? 'class="active"' : '' ?>>
                    <a href="<?= Url::toRoute(['admin/edit']) ?>">
                        <span class="glyphicon glyphicon-pencil"></span>
                        <?= Yii::t('admin', 'Услуги и стоимость') ?>
                    </a>
                </li>
                <li <?= Yii::$app->controller->action->id == 'leads' ? 'class="active"' : '' ?>>
                    <a href="<?= Url::toRoute(['admin/leads']) ?>">
                        <span class="glyphicon glyphicon-flash"></span>
                        <?= Yii::t('admin', 'Заявки') ?>
                    </a>
                </li>
                <li <?= Yii::$app->controller->action->id == 'contacts' ? 'class="active"' : '' ?>>
                    <a href="<?= Url::toRoute(['admin/contacts']) ?>">
                        <span class="glyphicon glyphicon-info-sign"></span>
                        <?= Yii::t('admin', 'Контакты') ?>
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href id="current-user" data-id="<?= Yii::$app->user->id ?>" data-href="<?= Url::toRoute(['admin/users']) ?>">
                        <span class="glyphicon glyphicon-user"></span>
                        <?= User::getName() ?>
                    </a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-flag"></span>
                        <?= Language::getView() ?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <?php foreach (Language::getLanguages() as $langView => $langCode): ?>
                        <li <?= $langCode == Yii::$app->language ? 'class="active"' : '' ?>>
                            <a href="<?= Url::current(['language' => $langCode])?>">
                                [<?= strtoupper($langView) ?>]
                                <?= Content::get(CONTENT_LANGUAGE_NAME, Language::findOne(['code' => $langCode])->id, $langCode) ?>
                            </a>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
                <li class="dropdown <?= in_array(Yii::$app->controller->action->id, ['settings', 'languages', 'users', 'translations']) ? 'active' : '' ?>">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-cog"></span>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li <?= Yii::$app->controller->action->id == 'settings' ? 'class="active"' : '' ?>>
                            <a href="<?= Url::toRoute(['admin/settings']) ?>">
                                <span class="glyphicon glyphicon-wrench"></span>
                                <?= Yii::t('admin', 'Настройки') ?>
                            </a>
                        </li>
                        <li <?= Yii::$app->controller->action->id == 'languages' ? 'class="active"' : 'class="disabled"' ?>>
                            <a href="<?= Url::toRoute(['admin/languages']) ?>">
                                <span class="glyphicon glyphicon-flag"></span>
                                <?= Yii::t('admin', 'Языки') ?>
                            </a>
                        </li>
                        <li <?= Yii::$app->controller->action->id == 'users' ? 'class="active"' : '' ?>>
                            <a href="<?= Url::toRoute(['admin/users']) ?>">
                                <span class="glyphicon glyphicon-user"></span>
                                <?= Yii::t('admin', 'Пользователи') ?>
                            </a>
                        </li>
                        <li <?= Yii::$app->controller->action->id == 'translations' ? 'class="active"' : '' ?>>
                            <a href="<?= Url::toRoute(['admin/translations']) ?>">
                                <span class="glyphicon glyphicon-globe"></span>
                                <?= Yii::t('admin', 'Переводы') ?>
                            </a>
                        </li>
                        <li <?= Yii::$app->controller->action->id == 'privacy-policy' ? 'class="active"' : 'class="disabled"' ?>>
                            <a href="<?= Url::toRoute(['admin/privacy-policy']) ?>">
                                <span class="glyphicon glyphicon-briefcase"></span>
                                <?= Yii::t('admin', 'Политика конфиденциальности') ?>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li <?= Yii::$app->controller->action->id == 'options' ? 'class="active"' : 'class="disabled"' ?>>
                            <a href="<?= Url::toRoute(['media/default/options']) ?>">
                                <span class="glyphicon glyphicon-scissors"></span>
                                <?= Yii::t('admin', 'Настройки кроппера') ?>
                            </a>
                        </li>
                        <li class="divider"></li>
                    </ul>
                </li>
                <li>
                    <a href id="site-preview" data-href="<?= Url::toRoute(['site/index'], true) ?>">
                        <span class="glyphicon glyphicon-eye-open"></span>
                    </a>
                </li>
                <li>
                    <a href="<?= Url::toRoute(['site/index']) ?>" target="_blank">
                        <span class="glyphicon glyphicon-home"></span>
                    </a>
                </li>
                <li>
                    <a href="<?= Url::toRoute(['admin/logout']) ?>">
                        <span class="glyphicon glyphicon-log-out"></span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

views/layouts/admin-main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\helpers\Url;
use app\assets\AdminAsset;

AdminAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="ajaxUrl" content="<?= Url::toRoute(['admin/ajax']) ?>">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div class="wrap">
    <?php if(!Yii::$app->user->isGuest): ?>
        <?= $this->render('admin-header') ?>
    <?php endif; ?>
    <div class="container-fluid" id="page-container">
        <?= $content ?>
    </div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/language-selector.php
<?php
/**
 * @var $this yii\web\View
 */

use app\modules\content\models\Content;
use app\models\Language;
use yii\helpers\Html;
use yii\helpers\Url;

?>
<div class="flex-box lang">
    <?php foreach (Language::getSiteLanguages() as $language): ?>
        <?= Html::a(Content::get(CONTENT_LANGUAGE_NAME, $language['id']), Url::current(['language' => $language['code']]), ['class' => Yii::$app->language == $language['code'] ? 'btn-lang active' : 'btn-lang']) ?>
    <?php endforeach; ?>
</div>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\helpers\Url;
use app\assets\AppAsset;
use app\models\Form;
use app\modules\content\models\Content;
use app\modules\content\BaseContent;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="ajaxUrl" content="<?= Url::toRoute(['site/ajax']) ?>">
    <?= Html::csrfMetaTags() ?>
    <?php $this->head() ?>
    <title><?= Html::encode($this->title) ?></title>
</head>
<body>
<?php $this->beginBody() ?>

<?= $this->render('header') ?>

<?= $content ?>

<?= $this->render('footer') ?>

<div class="flex-box justify-center align-center modal thq-modal" id="thq-modal">
    <div class="flex-box column inner">
        <button class="btn-close-modal"></button>

        <p class="font-style-secondary font-size-24 color-white fw-400 title"><?= Yii::t('app', 'Ваша заявка принята!') ?></p>

        <div class="h16px"></div>

        <p class="font-size-20 color-white fw-400 description"><?= Yii::t('app', 'Менеджер свяжется с Вами в ближайшее время') ?></p>
    </div>
</div>

<div class="flex-box justify-center align-center modal order-modal" id="order-modal">
    <div class="flex-box column inner">
        <button class="btn-close-modal"></button>
        <form class="flex-box column" data-type="<?= Form::TYPE_QUICK ?>">
            <input type="hidden" name="<?= Form::FIELD_PRODUCT ?>" value="" />
            <div class="mdc-text-field" data-mdc-auto-init="MDCTextField">
                <input class="mdc-text-field__input  mdc-theme--primary" type="text" name="<?= Form::FIELD_NAME ?>">
                <label class="mdc-floating-label mdc-theme--primary"><?= Yii::t('app', 'Имя') ?></label>
                <div class="mdc-line-ripple"></div>
            </div>
            <div class="mdc-text-field" data-mdc-auto-init="MDCTextField">
                <input class="mdc-text-field__input  mdc-theme--primary" type="text" name="<?= Form::FIELD_PHONE ?>">
                <label class="mdc-floating-label mdc-theme--primary"><?= Yii::t('app', 'Телефон') ?></label>
                <div class="mdc-line-ripple"></div>
            </div>

            <button type="submit" class="btn-type-1"><?= Yii::t('app', 'ПОДОБРАТЬ АВТО') ?></button>
        </form>
    </div>
</div>

<div class="flex-box justify-center align-center modal order-modal-extended" id="order-modal-extended">
    <div class="flex-box column inner">
        <button class="btn-close-modal"></button>
        <form class="flex-box column" data-type="<?= Form::TYPE_DEFAULT ?>">
            <input type="hidden" name="service" value="" />
            <?= $this->render('/site/forms/default-form') ?>
        </form>
    </div>
</div>

<script src="//unpkg.com/material-components-web@v4.0.0/dist/material-components-web.min.js"></script>

<script>
    function initMap() {
        initGoogleMap(
            parseFloat(<?= Content::get(CONTENT_CONTACT_MAP_LAT, BaseContent::OBJ_NOT_SET, BaseContent::LANG_NOT_SET) ?>),
            parseFloat(<?= Content::get(CONTENT_CONTACT_MAP_LNG, BaseContent::OBJ_NOT_SET, BaseContent::LANG_NOT_SET) ?>)
        );
    }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDocckFLbOj59qNlvEVktjbybt0X5CD74M&callback=initMap"></script>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>